# Generated by Django 5.2.10 on 2026-03-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_seller_product_baker_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bakerprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='baker_banners/'),
        ),
        migrations.AlterField(
            model_name='bakerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
