# Generated by Django 5.2.10 on 2026-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_bakerprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerprofile',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='baker_profiles/'),
        ),
        migrations.AlterField(
            model_name='bakerprofile',
            name='description',
            field=models.TextField(),
        ),
    ]
