# Generated by Django 5.2.10 on 2026-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_bakerprofile_banner_image_bakerprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BakerProfile',
        ),
    ]
