# Generated by Django 5.2.10 on 2026-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('baker', 'Baker'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
