# Generated by Django 5.2.10 on 2026-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_phone_no_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerprofile',
            name='aadhaar_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='aadhaar_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='fssai_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/fssai/'),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
