# Generated by Django 5.2.10 on 2026-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bakerprofile_aadhaar_image_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerprofile',
            name='seller_name',
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
